const agentsData = [
  {
    id: 1,
    name: "Rafay Qamar",
    company: "Qamar Group | REAL",
    location: "Chicago, IL",
    priceRange: "$18K - $2.1M",
    lastYearSales: 200,
    totalSales: 746,
    rating: 5.0,
    reviews: 680,
    team: true,
    image: "https://images.pexels.com/photos/7562311/pexels-photo-7562311.jpeg"
  },
  {
    id: 2,
    name: "Eva Diaz",
    company: "ExaRealty",
    location: "New York, NY",
    priceRange: "$30K - $1.2M",
    lastYearSales: 150,
    totalSales: 582,
    rating: 5.0,
    reviews: 450,
    team: false,
    image: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg"
  },
  {
    id: 3,
    name: "Sohail Khan",
    company: "City Point Realty",
    location: "Los Angeles, CA",
    priceRange: "$75K - $2.5M",
    lastYearSales: 180,
    totalSales: 620,
    rating: 4.9,
    reviews: 390,
    team: true,
    image: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg"
  },
  {
    id: 4,
    name: "Emily Watson",
    company: "BlueKey",
    location: "Chicago, IL",
    priceRange: "$90K - $1.5M",
    lastYearSales: 160,
    totalSales: 500,
    rating: 4.8,
    reviews: 320,
    team: false,
    image: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg"
  },
  {
    id: 5,
    name: "David Smith",
    company: "Metro Homes",
    location: "New York, NY",
    priceRange: "$40K - $1.3M",
    lastYearSales: 170,
    totalSales: 470,
    rating: 5.0,
    reviews: 410,
    team: true,
    image: "https://images.pexels.com/photos/2635315/pexels-photo-2635315.jpeg"
  },
  {
    id: 6,
    name: "Zain Ali",
    company: "eXp Realty",
    location: "Chicago, IL",
    priceRange: "$120K - $3.0M",
    lastYearSales: 210,
    totalSales: 880,
    rating: 4.7,
    reviews: 510,
    team: true,
    image: "https://images.pexels.com/photos/31956288/pexels-photo-31956288.jpeg"
  },
  {
    id: 7,
    name: "Aisha Khan",
    company: "Skyline Group",
    location: "Los Angeles, CA",
    priceRange: "$60K - $1.8M",
    lastYearSales: 130,
    totalSales: 360,
    rating: 5.0,
    reviews: 220,
    team: false,
    image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg"
  },
  {
    id: 8,
    name: "Omar Patel",
    company: "Qamar Group | REAL",
    location: "Chicago, IL",
    priceRange: "$95K - $2.0M",
    lastYearSales: 140,
    totalSales: 410,
    rating: 4.6,
    reviews: 280,
    team: true,
    image: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg"
  },
  {
    id: 9,
    name: "Maya Shah",
    company: "BlueKey",
    location: "New York, NY",
    priceRange: "$85K - $2.4M",
    lastYearSales: 190,
    totalSales: 520,
    rating: 4.9,
    reviews: 360,
    team: true,
    image: "https://images.pexels.com/photos/17041073/pexels-photo-17041073.jpeg"
  },
  {
    id: 10,
    name: "Nicholas Conteduca",
    company: "Metro Homes",
    location: "Los Angeles, CA",
    priceRange: "$70K - $2.1M",
    lastYearSales: 155,
    totalSales: 460,
    rating: 5.0,
    reviews: 300,
    team: false,
    image: "https://images.pexels.com/photos/1043473/pexels-photo-1043473.jpeg"
  },
  {
    id: 11,
    name: "Layla Brooks",
    company: "Urban Dwellings",
    location: "Austin, TX",
    priceRange: "$150K - $3.2M",
    lastYearSales: 120,
    totalSales: 300,
    rating: 4.6,
    reviews: 200,
    team: false,
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"
  },
  {
    id: 12,
    name: "Marcus Lee",
    company: "Bayfront Realty",
    location: "San Francisco, CA",
    priceRange: "$400K - $4.0M",
    lastYearSales: 210,
    totalSales: 620,
    rating: 4.9,
    reviews: 330,
    team: true,
    image: "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg"
  },
  {
    id: 13,
    name: "Nora Green",
    company: "Riverbend Group",
    location: "Denver, CO",
    priceRange: "$230K - $2.7M",
    lastYearSales: 180,
    totalSales: 540,
    rating: 4.7,
    reviews: 280,
    team: true,
    image: "https://images.pexels.com/photos/31806502/pexels-photo-31806502.jpeg"
  },
  {
    id: 14,
    name: "Jake Thomas",
    company: "Hillside Realty",
    location: "Phoenix, AZ",
    priceRange: "$140K - $2.1M",
    lastYearSales: 160,
    totalSales: 490,
    rating: 4.8,
    reviews: 290,
    team: false,
    image: "https://images.pexels.com/photos/1002406/pexels-photo-1002406.jpeg"
  },
  {
    id: 15,
    name: "Amira Sheikh",
    company: "NextHome Group",
    location: "Houston, TX",
    priceRange: "$210K - $2.9M",
    lastYearSales: 140,
    totalSales: 430,
    rating: 5.0,
    reviews: 350,
    team: true,
    image: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg"
  },
  {
    id: 16,
    name: "Brian Chen",
    company: "Skyline Properties",
    location: "Seattle, WA",
    priceRange: "$300K - $3.5M",
    lastYearSales: 190,
    totalSales: 560,
    rating: 4.9,
    reviews: 400,
    team: false,
    image: "https://images.pexels.com/photos/5397723/pexels-photo-5397723.jpeg"
  },
  {
    id: 17,
    name: "Sofia Romano",
    company: "Casa Realty",
    location: "Miami, FL",
    priceRange: "$110K - $1.9M",
    lastYearSales: 170,
    totalSales: 510,
    rating: 4.8,
    reviews: 310,
    team: true,
    image: "https://images.pexels.com/photos/29582944/pexels-photo-29582944.jpeg"
  },
  {
    id: 18,
    name: "Dylan West",
    company: "GreenLeaf Homes",
    location: "Nashville, TN",
    priceRange: "$180K - $2.3M",
    lastYearSales: 150,
    totalSales: 450,
    rating: 5.0,
    reviews: 275,
    team: false,
    image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg"
  },
  {
    id: 19,
    name: "Ava Singh",
    company: "UrbanEdge",
    location: "Philadelphia, PA",
    priceRange: "$130K - $1.7M",
    lastYearSales: 140,
    totalSales: 470,
    rating: 4.7,
    reviews: 260,
    team: true,
    image: "https://images.pexels.com/photos/31662639/pexels-photo-31662639.jpeg"
  },
  {
    id: 20,
    name: "Leo Hernandez",
    company: "MetroEdge Realty",
    location: "San Diego, CA",
    priceRange: "$200K - $2.6M",
    lastYearSales: 160,
    totalSales: 500,
    rating: 4.9,
    reviews: 320,
    team: false,
    image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg"
  }
];

export default agentsData;
